config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  resources :works
  resources :images
  resources :users
end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :work
	has_attached_file :media, styles: {
    thumb: '300x220>'
  }

  validates_attachment_content_type :media, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :works
end

app/models/work.rb
class Work < ActiveRecord::Base
	belongs_to :user
	has_one :image, :dependent => :destroy
	validates :title, :work_type, presence: true
	accepts_nested_attributes_for :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

	def index
		@images = Image.all
	end

	def show
		@image = Image.find(params[:id])
	end

	def new
		@image = Image.new
	end

	def create
    @image = Image.new(permitted_params)

    if @image.save
      redirect_to @image, notice: 'Friend was successfully created.'
     else
       render action: 'new'
    end
  end

  private

  def permitted_params
    params.require(:image).permit(:media)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@works = @user.works
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :authenticate_user!
end

app/controllers/works_controller.rb
class WorksController < ApplicationController

	def index
		@works = Work.all
	end

	def new
		@work = Work.new
		@image = Image.new
		@user = current_user
	end

	def create
		@work = Work.new(permitted_params)
		@image = Image.new(image_params)
		if @work.save
			@image.work_id = @work.id
			if @image.save
      	redirect_to user_path(@work.user_id), notice: 'Work was successfully created.'
      else
      	render action: 'new'
      end
    else
      render action: 'new'
    end
	end

	def show
		@work = Work.find(params[:id])
		@image = @work.image
	end

	private
	def permitted_params
    params.require(:work).permit(:title, :work_type, :description, :user_id)
  end

  def image_params
    params.require(:image).permit(:media)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/images/index.html.erb
<% @images.each do |image| %>
	<%= link_to image.id, image_path(image.id) %>
<% end %>

app/views/images/new.html.erb
<%= form_for @image do |f| %>

	<div class="field">
  	<%= f.label :media %><br />
  	<%= f.file_field :media %>
	</div>

	<%= f.submit 'Submit' %>

<% end %>

app/views/images/show.html.erb
<%= image_tag @image.media.url(:thumb) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ParlorFive</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>

<% @users.each do |user| %>
<%= link_to(user.email, user_path(user)) %>
<% end %>

app/views/users/show.html.erb
<%= @user.email %>

<%= link_to "Sumbit Art", new_work_path %>

<% @works.each do |work| %>
	<%= link_to work.title, work_path(work.id) %>
<% end %>

app/views/welcome/index.html.erb
<body>

  <div id="wrap" class="boxed">

  <header>
    <div class="container clearfix">
    
      <div class="logo one-third column" style="margin:0px; padding-top:10px;">
        <a href="/">
          <span style="font-family: 'League Gothic'; font-size:550%; color:white; margin-top:-20px;">PARLOR<span style="color:#00abc6;">FIVE</span></span>
        </a>
      </div>
      
      <div class="two-thirds column">
        <nav id="menu" class="navigation">
          <ul id="nav">
            <li><a href="/" id="home">Home</a></li>
            <li>
              <a href="${baseUrl}/pages/about.jsp" id="about">About</a>
              <ul>
                <li><a href="${baseUrl}/pages/about.jsp">About Us</a></li>
                <li><a href="${baseUrl}/pages/faq.jsp">FAQ</a></li>
                <li><a href="${baseUrl}/pages/contact.jsp">Contact</a></li>
                <li><a href="${baseUrl}/pages/subscribe.jsp">Subscribe</a></li>
                <li><a href="${baseUrl}/pages/artists.jsp">Demo Artists</a></li>
              </ul>
            </li>
            <li><a href="">Join</a></li> <!-- Open create account modal -->
          </ul>
        </nav>
      </div>
      
      <div class="sixteen columns"><hr /></div>
      
    </div><!-- End Container -->
  </header><!-- <<< End Header >>> -->
  
  <div class="container clearfix">
    
    <div class="recent-work gallery clearfix">
      <div class="slidewrap" >
        <div class="sixteen columns"> <h2 class="title">Recent Work <span class="line"></span></h2> </div>
        <ul class="slidecontrols">
          <li><a href="#sliderName" class="next">Next</a></li><li><a href="#sliderName" class="prev">Prev</a></li>
	      </ul>	
        <ul class="slider" id="sliderName">
          <li class="slide">	
            <div class="one-third column item">
                <div class="caption">
                <a href="single_project_1.html"><img src="images/img/thumbs/thumb-1.jpg" alt="" class="pic" />
                <span class="hover-effect link"></span></a>
                </div><!-- hover effect -->
                <h4><a href="single_project_1.html">MonsterUp</a></h4>
                <p>design ,graphic ,illustration</p>
            </div>
          </li><!-- End slide -->
        </ul>
      </div><!-- End slidewrap -->
    </div><!-- End recent-work -->
        
    <div id="welcome">
      <div class="sixteen columns">
        <div class="qoute">
          <div class="eleven columns omega">
            <h2>Interested in submitting work for the Parlor Five Beta?</h2>
            <p>We encourage all passionate artists to join!</p>
          </div>
          <div class="four columns alpha">
            <a href="join.jsp" class="link rounded">Join Now</a>
          </div>
        </div>
      </div>
    </div>
     
  </div>
  
  <footer>
    <div class="container">
    
      <div class="eight columns">
        <div class="about">
          <h3 class="title">About Us<span class="line"></span></h3>
          <p>
          Parlor Five is a platform developed by artists for artists. By facilitating a closer, more meaningful interaction within the artistic community, we hope to provide both exposure for up-and-coming artists and inspiration for art enthusiasts.
          </p>
        </div>
      </div>
      
      <div class="eight columns">
        <div class="subscribe">
          <h3 class="title">Subscribe<span class="line"></span></h3>
          <p>Subscribe to our e-mail newsletter to receive updates.</p>
          <div class="alert error hideit" style="display:none;">
          Email entered was invalid.
          <span class="close"></span>
        </div>
          <form action="/pages/newsletter/subscribe.jsp" method="POST" >
            <input type="text" name="email" class="mail" value="Enter your Email" onBlur="if(this.value == '') { this.value = 'Enter your Email'; }" 
            onfocus="if(this.value == 'Enter your Email') { this.value = ''; }"/>
            <input style="margin-right:17px;" type="submit" value="Submit" class="submit rounded_small" />
          </form>
        </div>
      </div>
      
      <div class="sixteen columns"><hr class="bottom" /></div>
      
      <div class="ten columns"><span class="copyright">
      &copy; Copyright 2013 <a href="/">Parlor Five</a>. All Rights Reserved. | <a href="/pages/privacy.jsp">Privacy Policy</a> | <a href="/pages/terms.jsp">Terms & Conditions</a></span></div>
      
      <div class="six columns">
        <div class="social">
          <a href="https://www.facebook.com/ParlorFive" target="_blank"><img src="/resources/img/icons/facebook.png" alt="" /></a>
          <a href="https://twitter.com/ParlorFive" target="_blank"><img src="/resources/img/icons/twitter.png" alt="" /></a>
        </div>
      </div>
    
    </div><!-- End container -->
  </footer><!-- <<< End Footer >>> -->
  
  </div><!-- End wrap -->
    
</body>
</html>

app/views/works/index.html.erb
<h1>Works</h1>

app/views/works/new.html.erb
<%= form_for @work do |f| %>

	<%= f.label :title %>
  <%= f.text_field :title %>
  
  <%= f.label :type %>
  <%= f.text_field :work_type %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= fields_for @image do |image_form| %>
  	<%= image_form.label :media %><br />
  	<%= image_form.file_field :media %>
  <% end %>

  <%= f.hidden_field :user_id, :value => @user.id %>

	<%= f.submit 'Submit' %>

<% end %>

app/views/works/show.html.erb
<div class="container gallery clearfix">
  
	<% if !work.title.empty? %>
  	<div class="sixteen columns">
  		<h1 class="page-title"><%= @work.title %><span class="line"></span></h1>
  	</div>
 	<% end %>
   
  <div class="sixteen columns top-2">
  	<h2 class="title">By 
  		<!-- <a style="cursor:pointer; color:#00abc6;" href="profile.jsp?id=<%=a.accountId %>"><%= @artist.name %></a> -->
  		<span class="line"></span>
  	</h2>
  </div>

   <div class="twelve columns top bottom">

	<%= image_tag @image.media.url() %>

  </div>
   
  <div class="four columns bottom project-details">
   	<%if !@work.description.empty? %>
	    <h2 class="title top-5  bottom-2">Description <span class="line"></span></h2>
	    <div class="about-project">
	      <p><%= @work.description %></p>
	    </div>
    <% end %>
     
  	<div class="clearfix"></div>
   
  	<h2 class="title bottom-2">Tags <span class="line"></span></h2>
   
    <div class="popular-tags top">
    	<% if tags != null %>
      	<% tags.each do |tag| %>
      		<a href="/tag/#{tag.id}"><%= tag.label %></a>
      	<% end %>
    	<% end %>
    </div>
  </div>

</div>